using OnlineMuhasebeServer.Domain.AppEntities;
using OnlineMuhasebeServer.Domain.Repositories.GenericRepositories.AppDbcontext;


namespace OnlineMuhasebeServer.Domain.Repositories.AppDbContext.MainRoleAndRoleRelationshipRepositories;

public interface IMainRoleAndRoleRelationshipQueryRepository : IAppQueryRepository<MainRoleAndRoleRelationship>
{

}
